/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package week4;

import java.io.*;
import java.security.*;
import java.security.spec.*;
import javax.crypto.*;
import javax.crypto.spec.*;

/**
 *
 * @author Administrator
 */
public class Alice extends javax.swing.JFrame {

    /**
     * Creates new form Alice
     */
    public Alice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKhoaAlice = new javax.swing.JTextField();
        txtKhoaBoB = new javax.swing.JTextField();
        txtKhoaKAB = new javax.swing.JTextField();
        txtMaHoaKAB = new javax.swing.JTextField();
        btnTaoKhoaA = new javax.swing.JButton();
        btnHienThiKB = new javax.swing.JButton();
        btnKhoaChung = new javax.swing.JButton();
        btnMaHoaKAB = new javax.swing.JButton();
        btnMaHoa_GiaiMa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Khóa BoB");

        jLabel2.setText("Khóa Alice");

        jLabel3.setText("Khóa KAB");

        jLabel4.setText("Mã hóa KAB");

        btnTaoKhoaA.setText("Tạo Khóa A");
        btnTaoKhoaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoKhoaAActionPerformed(evt);
            }
        });

        btnHienThiKB.setText("Hiển thị KB");
        btnHienThiKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiKBActionPerformed(evt);
            }
        });

        btnKhoaChung.setText("Khóa chung");
        btnKhoaChung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaChungActionPerformed(evt);
            }
        });

        btnMaHoaKAB.setText("Mã hóa KAB");
        btnMaHoaKAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaKABActionPerformed(evt);
            }
        });

        btnMaHoa_GiaiMa.setText("Mã hóa/Giải mã");
        btnMaHoa_GiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoa_GiaiMaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Alice");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtKhoaKAB, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKhoaChung))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMaHoaKAB, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMaHoaKAB))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtKhoaBoB, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnHienThiKB))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtKhoaAlice, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTaoKhoaA)))
                                .addGap(0, 2, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(btnMaHoa_GiaiMa)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel2)
                    .addContainerGap(469, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKhoaAlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaoKhoaA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKhoaBoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHienThiKB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKhoaKAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhoaChung))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaHoaKAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaHoaKAB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMaHoa_GiaiMa)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jLabel2)
                    .addContainerGap(190, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    KeyAgreement aliceKeyAgree;
    PublicKey bobPubKey;
    SecretKey aliceDesKey;
    Cipher aliceCipher;
    private void btnTaoKhoaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoKhoaAActionPerformed
        // TODO add your handling code here:
        try{ 
            AlgorithmParameterGenerator paramGen = AlgorithmParameterGenerator.getInstance("DH"); 
            paramGen.init(512); 
            AlgorithmParameters params = paramGen.generateParameters(); 
            DHParameterSpec dhSkipParamSpec = (DHParameterSpec)params.getParameterSpec(DHParameterSpec.class); 
            System.out.println("Generating a DH KeyPair..."); 
            KeyPairGenerator aliceKpairGen = KeyPairGenerator.getInstance("DH"); 
            aliceKpairGen.initialize(dhSkipParamSpec); 
            KeyPair aliceKpair = aliceKpairGen.generateKeyPair(); 
            System.out.println("Initializing the KeyAgreement Engine with DH private key"); 
            aliceKeyAgree = KeyAgreement.getInstance("DH");
            aliceKeyAgree.init(aliceKpair.getPrivate());
            
            byte[] alicePubKeyEnc = aliceKpair.getPublic().getEncoded(); 
            FileOutputStream fos = new FileOutputStream("D:/A.pub"); 
            fos.write(alicePubKeyEnc); fos.close(); 
            txtKhoaAlice.setText(alicePubKeyEnc.toString()); 
        }
        catch(Exception ex){ 
        }       
    }//GEN-LAST:event_btnTaoKhoaAActionPerformed

    private void btnHienThiKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiKBActionPerformed
        // TODO add your handling code here:
        try{
            FileInputStream fis = new FileInputStream("D:/B.pub");
            byte[] bkeyP=new byte[fis.available()]; 
            fis.read(bkeyP); 
            fis.close(); 
            txtKhoaBoB.setText(bkeyP.toString()); 
        } 
        catch(Exception ex){ 
        }
    }//GEN-LAST:event_btnHienThiKBActionPerformed

    private void btnKhoaChungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaChungActionPerformed
        // TODO add your handling code here:
        try{ 
            FileInputStream fis=new FileInputStream("D:/B.pub"); 
            byte[] bobPubKeyEnc=new byte[fis.available()]; 
            fis.read(bobPubKeyEnc); fis.close(); 
            KeyFactory aliceKeyFac = KeyFactory.getInstance("DH"); 
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec(bobPubKeyEnc); 
            bobPubKey = aliceKeyFac.generatePublic(x509KeySpec); 
            System. out.println("Executing PHASES of key agreement..."); 
            aliceKeyAgree.doPhase(bobPubKey, true); 
            byte[] aliceSharedSecret = aliceKeyAgree.generateSecret(); 
            System.out.println("khoa chung: secret (DEBUG ONLY):" + CryptoUtil.toHexString(aliceSharedSecret)); 
            txtKhoaKAB.setText(CryptoUtil.toHexString(aliceSharedSecret)); 
        } 
        catch(Exception ex){ 
        
        } 

    }//GEN-LAST:event_btnKhoaChungActionPerformed

    private void btnMaHoaKABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaKABActionPerformed
        // TODO add your handling code here:
        try{ 
            aliceKeyAgree.doPhase(bobPubKey, true); 
            aliceDesKey = aliceKeyAgree.generateSecret("DES"); 
            txtMaHoaKAB.setText(aliceDesKey.toString()); // khoa chung A-B 
            BufferedWriter bw = null; //ghi van ban da ma hoa 
            String fileName = "D:\\KhoaA.txt"; //luu van ban 
            bw = new // van ban sau khi ma hoa 
            BufferedWriter(new FileWriter(fileName)); // ghi van ban 
            bw.write(aliceDesKey.toString()); 
            bw.close(); 
        }
        catch(Exception ex){
        } 
    }//GEN-LAST:event_btnMaHoaKABActionPerformed

    private void btnMaHoa_GiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoa_GiaiMaActionPerformed
        // TODO add your handling code here:
        DESCS des = new DESCS();
        des.setVisible(true);
    }//GEN-LAST:event_btnMaHoa_GiaiMaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienThiKB;
    private javax.swing.JButton btnKhoaChung;
    private javax.swing.JButton btnMaHoaKAB;
    private javax.swing.JButton btnMaHoa_GiaiMa;
    private javax.swing.JButton btnTaoKhoaA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtKhoaAlice;
    private javax.swing.JTextField txtKhoaBoB;
    private javax.swing.JTextField txtKhoaKAB;
    private javax.swing.JTextField txtMaHoaKAB;
    // End of variables declaration//GEN-END:variables
}
