/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab1_bai4;

/**
 *
 * @author Administrator
 */
public class fMain extends javax.swing.JFrame {

    char pf[][] = {{'M','O','N','A','R'},
                    {'C','H','Y','B','D'},
                    {'E','F','G','I','K'},
                    {'L','P','Q','S','T'},
                    {'U','V','W','X','Z'}};
    /**
     * Creates new form fMain
     */
    public fMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPlain = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtKey = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEncrypt = new javax.swing.JTextArea();
        btnEncrypt = new javax.swing.JButton();
        btnDecrypt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bản rõ");

        txtPlain.setText("Hutech");

        jLabel2.setText("Khóa");

        txtKey.setText("MONARCHY");

        jLabel3.setText("Bản mã");

        txtEncrypt.setColumns(20);
        txtEncrypt.setRows(5);
        jScrollPane1.setViewportView(txtEncrypt);

        btnEncrypt.setText("Mã hóa");
        btnEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptActionPerformed(evt);
            }
        });

        btnDecrypt.setText("Giải mã");
        btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtPlain, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEncrypt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDecrypt)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPlain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEncrypt)
                    .addComponent(btnDecrypt))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptActionPerformed
        // TODO add your handling code here:
        String banro = this.txtPlain.getText();
        banro = banro.toUpperCase();
        banro = banro.replace('J', 'I');
        String banma = mahoa(banro);
        txtEncrypt.setText(banma);
    }//GEN-LAST:event_btnEncryptActionPerformed

    private String mahoa(String banro)
    {
        int n = banro.length();
        int i = 0;
        
        String banma = "";
        char a,b;
        
        while (i < n) {
            if (i == n-1)
            {
                a = banro.charAt(i);
                b = 'X';
                i++;
            }
            else
            {
                a = banro.charAt(i);
                b = banro.charAt(i+1);
                
                if (a == b) {
                    b = 'X';
                    i++;
                }
                else {
                    i+=2;
                }
            }
            banma+=thaythe(a,b);
        }
        return banma;
    }
    
    private String thaythe(char a, char b)
    {
        String vta = timViTri(a);
        String vtb = timViTri(b);
        
        char x, y;
        if (vta.charAt(0)==vtb.charAt(0))
        {
            x = pf[vta.charAt(0)-'0'][((vta.charAt(1)-'0')+1)%5];
            y = pf[vtb.charAt(0)-'0'][((vtb.charAt(1)-'0')+1)%5];
        }
        else if (vta.charAt(1)==vtb.charAt(1)) {
            x = pf[((vta.charAt(0)-'0')+1)%5][vta.charAt(1)-'0'];
            y = pf[((vtb.charAt(0)-'0')+1)%5][vtb.charAt(1)-'0'];
        }
        else
        {
            x = pf[vta.charAt(0)-'0'][vtb.charAt(1)-'0'];
            y = pf[vtb.charAt(0)-'0'][vta.charAt(1)-'0'];
        }
        
        return x + "" + y;
    }
    
    private String timViTri(char a) {
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                if (pf[i][j] == a) return i + "" + j;
            }
        }
        return "";
    }
    
    private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
        // TODO add your handling code here:
        String banma = this.txtEncrypt.getText();
        String banro = giaiMa(banma);
        int n = banro.length();
        
        String br  = "";
        for (int i = 0; i < n-2; i+=2) {
            if (banro.charAt(i) == banro.charAt(i+2)) br+= banro.charAt(i);
            else br+= banro.charAt(i) + "" + banro.charAt(i+1);
        }
        if (banro.charAt(n-1) == 'X') br += banro.charAt(n-2);
        else br += banro.charAt(n-2) + "" + banro.charAt(n-1);
        this.txtPlain.setText(br);
        
    }//GEN-LAST:event_btnDecryptActionPerformed
    
    private String giaiMa(String banma) {
        int n = banma.length();
        String banro = "";
        char a, b;
        for (int i = 0; i < n; i+=2)
        {
            a = banma.charAt(i);
            b = banma.charAt(i+1);
            banro += thayTheNguoc(a, b);
        }
        return banro;
    }
    
    private String thayTheNguoc(char a, char b) {
        String vta = timViTri(a);
        String vtb = timViTri(b);
        
        char x, y;
        if (vta.charAt(0)==vtb.charAt(0))
        {
            x = pf[vta.charAt(0)-'0'][((vta.charAt(1)-'0')-1+5)%5];
            y = pf[vtb.charAt(0)-'0'][((vtb.charAt(1)-'0')-1+5)%5];
        }
        else if (vta.charAt(1)==vtb.charAt(1)) {
            x = pf[((vta.charAt(0)-'0')-1+5)%5][vta.charAt(1)-'0'];
            y = pf[((vtb.charAt(0)-'0')-1+5)%5][vtb.charAt(1)-'0'];
        }
        else
        {
            x = pf[vta.charAt(0)-'0'][vtb.charAt(1)-'0'];
            y = pf[vtb.charAt(0)-'0'][vta.charAt(1)-'0'];
        }
        
        return x + "" + y;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecrypt;
    private javax.swing.JButton btnEncrypt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtEncrypt;
    private javax.swing.JTextField txtKey;
    private javax.swing.JTextField txtPlain;
    // End of variables declaration//GEN-END:variables
}
